config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView

from member import views as member_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # post
    path('', post_views.PostListView.as_view(), name='main'),
    path('create/', post_views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/update/', post_views.PostUpdateView.as_view(), name='update'),

    # like
    path('like/', post_views.toggle_like, name='toggle_like'),

    # auth
    path('signup/', member_views.SignupView.as_view(), name='signup'),
    path('verify/', member_views.verify_email, name='verify_email'),
    path('login/', member_views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # search
    path('search/', post_views.search, name='search'),

    # include
    path('comment/', include('post.comment_urls')),
    path('profile/', include('member.urls')),
    path('oauth/', include('member.oauth_urls')),

    #path('account/', include('django.contrib.auth.ruls'))
    # path('signup/done/', TemplateView.as_view(template_name='auth/signup_done.html'), name='signup_done'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path('<str:slug>/', views.UserProfileView.as_view(), name='detail'),
    path('<int:pk>/follow/', views.UserFollowingView.as_view(), name='follow'),
]

templates/search/search.html
{% extends 'base.html' %}
{% block content %}
    {% include 'include/search_form.html' %}
{% endblock %}

templates/search/search_tag.html
{% extends 'base.html' %}
{% block style %}
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />
{% endblock %}
{% block content %}
    <h1>tag</h1>
    {% include 'include/search_form.html' %}

    <div class="row mt-2">
        {% for post in object_list %}
            <div class="col-4 my-2">
                <div class="swiper">
                    <div class="border-1 swiper-wrapper">
                        {% for post_image in post.images.all %}
                            <div class="swiper-slide">
                                <img class="img-fluid post-image" src="{{ post_image.image.url }}" alt="">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-pagination"></div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script>
        const swiper = new Swiper('.swiper', {
          // Optional parameters
          direction: 'horizontal',
          loop: false,

          // If we need pagination
          pagination: {
            el: '.swiper-pagination',
          },

        });
    </script>
{% endblock %}

templates/search/search_user.html
{% extends 'base.html' %}
{% block content %}
    <h1>user</h1>
    {% include 'include/search_form.html' %}
    <div>
        <ul>
            {% for user in object_list %}
                <div class="my-4">
                    <a href="{% url 'profile:detail' user.nickname %}" class="text-decoration-none text-black">
                        <span class="p-2 border rounded-circle me-2">
                            <i class="fa-solid fa-user" style="width: 16px; padding-left: 3px;"></i>
                        </span>
                        {{ user.nickname }}
                    </a>
                </div>
            {% endfor %}
        </ul>
    </div>
{% endblock %}